- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

#robots
- ros_topic_name: "/twix/joint_states"
  gz_topic_name: "/world/hello_world/model/twix/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/twix/tf"
  gz_topic_name: "/model/twix/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/twirl/joint_states"
  gz_topic_name: "/world/hello_world/model/twirl/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/twirl/tf"
  gz_topic_name: "/model/twirl/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

#gazebo
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/my_robot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/odom"
  gz_topic_name: "/model/my_robot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# - ros_topic_name: "/camera/camera_info"
#   gz_topic_name: "/camera/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "gz.msgs.CameraInfo"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/camera/image_raw"
#   gz_topic_name: "/camera/image_raw"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS

# cameras
- ros_topic_name: "/twix_camera/camera_info"
  gz_topic_name: "/twix_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/twix_camera/image_raw"
  gz_topic_name: "/twix_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/twirl_camera/camera_info"
  gz_topic_name: "/twirl_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/twirl_camera/image_raw"
  gz_topic_name: "/twirl_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# irs
- ros_topic_name: "/twix_ir/camera_info"
  gz_topic_name: "/twix_ir/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/twix_ir/image_raw"
  gz_topic_name: "/twix_ir/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/twirl_ir/camera_info"
  gz_topic_name: "/twirl_ir/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/twirl_ir/image_raw"
  gz_topic_name: "/twirl_ir/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# lidars
- ros_topic_name: "/twix/scan"
  gz_topic_name: "/twix/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/twirl/scan"
  gz_topic_name: "/twirl/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# FOR CONTROLLING  (TESTING VIA TELEOP KEYBOARD)
- ros_topic_name: "/twirl/cmd_vel"
  gz_topic_name: "/twirl/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/twix/cmd_vel"
  gz_topic_name: "/twix/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

#ESPs ?